---
name: Build Docker Images
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow weekly on Thursday as well as on pushes to the default
  # branch that include changes to the services/ directory.
  schedule:
    - cron: '22 20 * * 4'
  push:
    branches:
      - main
    paths:
      - 'services/**'
  pull_request:
    paths:
      - 'services/**'

jobs:
  image-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.3, 7.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate docker images
        if: ${{ github.event_name == 'pull_request' }}
        run: docker build services/php-apache/ --build-arg PHP_VERSION=${{ matrix.php }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: services/php-apache
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_args: PHP_VERSION=${{ matrix.php }}
          repository: chromatichq/php-apache
          tags: ${{ matrix.php }}
