---
name: Build Docker Images
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow weekly on Thursday as well as on pushes to the default
  # branch that include changes to the services/ directory.
  schedule:
    - cron: '22 20 * * 4'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'services/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'services/**'

jobs:
  image-build-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["php-apache", "php-apache-n"]
        php: [7.3, 7.4, "8.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Validate docker images
        if: ${{ github.event_name == 'pull_request' }}
        run: docker build services/${{ matrix.service }}/ --build-arg PHP_VERSION=${{ matrix.php }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: services/${{ matrix.service }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_args: PHP_VERSION=${{ matrix.php }}
          repository: chromatichq/${{ matrix.service }}
          tags: ${{ matrix.php }}

  # DO NOT MERGE: This temp job re-generates the php-apache-n image in
  # Dockerhub on every PR.
  image-build-php-temp:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["php-apache-n"]
        php: ["8.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: services/${{ matrix.service }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_args: PHP_VERSION=${{ matrix.php }}
          repository: chromatichq/${{ matrix.service }}
          tags: ${{ matrix.php }}

  image-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [node]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Validate docker images
        if: ${{ github.event_name == 'pull_request' }}
        run: docker build services/${{ matrix.service }}/

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          path: services/${{ matrix.service }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: chromatichq/${{ matrix.service }}
          tags: latest
