---
name: Build Docker Images
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow weekly on Thursday as well as on pushes to the default
  # branch that include changes to the services/ directory.
  schedule:
    - cron: '22 20 * * 4'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'services/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'services/**'

jobs:
  image-build-php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.3, 7.4]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: services/php-apache/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: chromatichq/php-apache:${{ matrix.php }}

  image-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [node]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: services/${{ matrix.service }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: chromatichq/${{ matrix.service }}:latest
