---
name: Build Docker Images
on:  # yamllint disable-line rule:truthy
  # Trigger the workflow weekly on Thursday as well as on pushes to the default
  # branch that include changes to the services/ directory.
  schedule:
    - cron: '22 20 * * 4'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - 'services/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'services/**'

jobs:
  # Deleted other jobs to keep builds nice and snappy. Restore these before
  # merging into main branch!

  # Temporary job to build an image from the PR branch. Image intended to more
  # easily experiment with using nvm to install Node.
  image-build-node-via-nvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: services/php-apache-nvm-test
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_args: PHP_VERSION=${{ matrix.php }}
          repository: chromatichq/php-apache-nvm-test
          tags: ${{ matrix.php }}
